"""
File Handling: Reading, writing, streaming large files, pathlib, and CSV/JSON/binary.
"""
import csv
import json
import io
import os
import struct
import hashlib
import shutil
from pathlib import Path
from typing import Iterator, Generator

# ═══════════════════════════════════════════
# 1. pathlib patterns
# ═══════════════════════════════════════════
def pathlib_tour(base: Path):
    print("=== pathlib tour ===")
    print(f"  parts:   {base.parts}")
    print(f"  name:    {base.name}")
    print(f"  stem:    {base.stem}")
    print(f"  suffix:  {base.suffix}")
    print(f"  parent:  {base.parent}")
    print(f"  exists:  {base.exists()}")

    # Build paths
    data_dir = base / "data"
    data_dir.mkdir(exist_ok=True)
    readme = data_dir / "README.md"
    readme.write_text("# Demo\nGenerated by pathlib_tour.")

    print(f"  created: {readme}")
    print(f"  size:    {readme.stat().st_size} bytes")

    # Glob patterns
    py_files = list(base.glob("*.py"))
    print(f"  .py files in base: {len(py_files)}")

    all_py = list(base.rglob("*.py"))
    print(f"  .py files (recursive): {len(all_py)}")

    # Resolve absolute path
    print(f"  absolute: {readme.resolve()}")

    # Cleanup
    shutil.rmtree(data_dir)

# ═══════════════════════════════════════════
# 2. Streaming large text files
# ═══════════════════════════════════════════
def stream_lines(path: Path, encoding: str = "utf-8") -> Iterator[str]:
    """Stream lines without loading entire file into memory."""
    with path.open(encoding=encoding) as fh:
        for line in fh:
            yield line.rstrip("\n")

def word_count(path: Path) -> dict[str, int]:
    """Count word frequencies streaming a file."""
    counts: dict[str, int] = {}
    for line in stream_lines(path):
        for word in line.split():
            word = word.strip(".,!?;:\"'").lower()
            if word:
                counts[word] = counts.get(word, 0) + 1
    return counts

def line_count(path: Path) -> int:
    """Count lines efficiently with read()."""
    with path.open("rb") as fh:
        return sum(1 for _ in fh)

def find_in_file(path: Path, pattern: str) -> list[tuple[int, str]]:
    """Find all lines containing pattern, return (lineno, line)."""
    results = []
    for i, line in enumerate(stream_lines(path), 1):
        if pattern.casefold() in line.casefold():
            results.append((i, line))
    return results

# ═══════════════════════════════════════════
# 3. CSV handling
# ═══════════════════════════════════════════
def write_csv(path: Path, rows: list[dict]) -> None:
    if not rows: return
    with path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=rows[0].keys())
        writer.writeheader()
        writer.writerows(rows)

def read_csv(path: Path) -> list[dict]:
    with path.open(encoding="utf-8") as fh:
        return list(csv.DictReader(fh))

def csv_to_json(csv_path: Path, json_path: Path, indent: int = 2) -> None:
    rows = read_csv(csv_path)
    json_path.write_text(json.dumps(rows, indent=indent), encoding="utf-8")

class CSVProcessor:
    """Stream-process a CSV file without loading it all into memory."""

    def __init__(self, path: Path):
        self.path = path

    def filter_rows(self, pred) -> Generator[dict, None, None]:
        with self.path.open(encoding="utf-8") as fh:
            for row in csv.DictReader(fh):
                if pred(row):
                    yield row

    def aggregate(self, key_col: str, value_col: str) -> dict[str, float]:
        totals: dict[str, float] = {}
        with self.path.open(encoding="utf-8") as fh:
            for row in csv.DictReader(fh):
                k = row[key_col]
                totals[k] = totals.get(k, 0.0) + float(row[value_col])
        return totals

# ═══════════════════════════════════════════
# 4. JSON patterns
# ═══════════════════════════════════════════
def read_json_file(path: Path) -> dict | list:
    return json.loads(path.read_text(encoding="utf-8"))

def write_json_file(path: Path, data, indent: int = 2) -> None:
    path.write_text(json.dumps(data, indent=indent, ensure_ascii=False), encoding="utf-8")

def stream_ndjson(path: Path) -> Iterator[dict]:
    """Stream newline-delimited JSON (NDJSON)."""
    with path.open(encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line:
                yield json.loads(line)

def write_ndjson(path: Path, records: list[dict]) -> None:
    with path.open("w", encoding="utf-8") as fh:
        for record in records:
            fh.write(json.dumps(record) + "\n")

# ═══════════════════════════════════════════
# 5. Binary file handling
# ═══════════════════════════════════════════
# Simple binary format: header (4 bytes magic, 4 bytes version, 4 bytes record_count)
MAGIC = b"SBIN"
VERSION = 1

def write_binary(path: Path, records: list[tuple[int, float, str]]) -> None:
    """Write binary file: header + records (int32, float64, 32-byte UTF-8 name)."""
    with path.open("wb") as fh:
        fh.write(struct.pack(">4sII", MAGIC, VERSION, len(records)))
        for record_id, score, name in records:
            name_bytes = name.encode("utf-8")[:32].ljust(32, b"\x00")
            fh.write(struct.pack(">Id32s", record_id, score, name_bytes))

def read_binary(path: Path) -> list[tuple[int, float, str]]:
    records = []
    with path.open("rb") as fh:
        magic, version, count = struct.unpack(">4sII", fh.read(12))
        assert magic == MAGIC, f"Bad magic: {magic!r}"
        for _ in range(count):
            record_id, score, name_bytes = struct.unpack(">Id32s", fh.read(44))
            records.append((record_id, score, name_bytes.rstrip(b"\x00").decode()))
    return records

# ═══════════════════════════════════════════
# 6. File checksum and safe write
# ═══════════════════════════════════════════
def sha256_file(path: Path, chunk_size: int = 65536) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        while chunk := fh.read(chunk_size):
            h.update(chunk)
    return h.hexdigest()

def atomic_write(path: Path, content: str, encoding: str = "utf-8") -> None:
    """Write to a temp file, then rename (atomic on POSIX, best-effort on Windows)."""
    tmp = path.with_suffix(path.suffix + ".tmp")
    try:
        tmp.write_text(content, encoding=encoding)
        tmp.replace(path)
    except Exception:
        tmp.unlink(missing_ok=True)
        raise

def safe_copy(src: Path, dst: Path) -> None:
    """Copy with checksum verification."""
    shutil.copy2(src, dst)
    if sha256_file(src) != sha256_file(dst):
        dst.unlink()
        raise IOError(f"Checksum mismatch after copying {src} → {dst}")

# ═══════════════════════════════════════════
# DEMO
# ═══════════════════════════════════════════
if __name__ == "__main__":
    import tempfile, os

    with tempfile.TemporaryDirectory() as tmp_dir:
        base = Path(tmp_dir)

        # CSV
        print("=== CSV ===")
        employees = [
            {"name":"Alice",  "dept":"Eng",   "salary":"90000"},
            {"name":"Bob",    "dept":"Eng",   "salary":"85000"},
            {"name":"Carol",  "dept":"Sales", "salary":"70000"},
            {"name":"Dave",   "dept":"Sales", "salary":"72000"},
            {"name":"Eve",    "dept":"HR",    "salary":"65000"},
        ]
        csv_path = base / "employees.csv"
        write_csv(csv_path, employees)
        rows = read_csv(csv_path)
        print(f"  Read {len(rows)} rows from CSV")

        proc = CSVProcessor(csv_path)
        eng = list(proc.filter_rows(lambda r: r["dept"] == "Eng"))
        print(f"  Engineering: {[r['name'] for r in eng]}")
        dept_totals = proc.aggregate("dept", "salary")
        for dept, total in sorted(dept_totals.items()):
            print(f"  {dept}: ${total:,.0f}")

        # JSON
        print("\n=== JSON ===")
        json_path = base / "data.json"
        write_json_file(json_path, employees)
        loaded = read_json_file(json_path)
        print(f"  Written and read back {len(loaded)} records")

        ndjson_path = base / "events.ndjson"
        write_ndjson(ndjson_path, [{"event":"login","user":"alice"},
                                   {"event":"query","user":"bob"}])
        events = list(stream_ndjson(ndjson_path))
        print(f"  NDJSON: {events}")

        # Binary
        print("\n=== Binary ===")
        bin_path = base / "records.bin"
        original = [(1, 98.7, "Alice"), (2, 87.3, "Bob"), (3, 95.1, "Carol")]
        write_binary(bin_path, original)
        loaded_bin = read_binary(bin_path)
        print(f"  Written: {original}")
        print(f"  Read:    {loaded_bin}")
        assert original == loaded_bin

        # Checksum
        print("\n=== Checksum ===")
        checksum = sha256_file(csv_path)
        print(f"  SHA-256 of CSV: {checksum[:16]}...")

        # Atomic write
        target = base / "config.json"
        atomic_write(target, '{"debug": false}')
        print(f"  Atomic write: {target.read_text()}")

        # Line / word count
        print("\n=== Stream counts ===")
        lines = line_count(csv_path)
        print(f"  Lines in CSV (incl. header): {lines}")

        find_results = find_in_file(csv_path, "eng")
        print(f"  Lines with 'eng': {len(find_results)}")

        # pathlib tour
        pathlib_tour(base)
