"""
Virtual Environments and Packaging: pip internals, constraints, and lock files.
"""
import subprocess
import sys
import json
from pathlib import Path

# ─────────────────────────────────────────────────────────
# 1. pip from Python
# ─────────────────────────────────────────────────────────
class PipManager:
    """Invoke pip programmatically as a subprocess."""

    def __init__(self, python: str | None = None):
        self.python = python or sys.executable

    def _run(self, args: list[str]) -> tuple[int, str, str]:
        cmd = [self.python, "-m", "pip"] + args
        result = subprocess.run(cmd, capture_output=True, text=True)
        return result.returncode, result.stdout, result.stderr

    def install(self, *packages: str, upgrade: bool = False,
                constraints: Path | None = None) -> bool:
        args = ["install"]
        if upgrade:
            args.append("--upgrade")
        if constraints:
            args += ["-c", str(constraints)]
        args += list(packages)
        code, out, err = self._run(args)
        if code != 0:
            print(f"pip install failed:\n{err}")
        return code == 0

    def uninstall(self, *packages: str) -> bool:
        code, _, err = self._run(["uninstall", "-y", *packages])
        return code == 0

    def list_packages(self) -> list[dict]:
        code, out, _ = self._run(["list", "--format=json"])
        if code != 0:
            return []
        return json.loads(out)

    def show(self, package: str) -> dict:
        code, out, _ = self._run(["show", package])
        if code != 0:
            return {}
        return dict(line.split(": ", 1) for line in out.strip().splitlines() if ": " in line)

    def freeze(self) -> list[str]:
        _, out, _ = self._run(["freeze"])
        return [line.strip() for line in out.splitlines() if line.strip()]

    def check(self) -> bool:
        """Check for dependency conflicts."""
        code, out, _ = self._run(["check"])
        print(out.strip() or "No conflicts.")
        return code == 0

    def outdated(self) -> list[dict]:
        _, out, _ = self._run(["list", "--outdated", "--format=json"])
        try:
            return json.loads(out)
        except json.JSONDecodeError:
            return []

# ─────────────────────────────────────────────────────────
# 2. requirements.txt patterns
# ─────────────────────────────────────────────────────────
REQUIREMENTS_PATTERNS = """
# requirements.txt — pinned for reproducibility
Django==4.2.7
djangorestframework==3.14.0
psycopg2-binary==2.9.9
redis==5.0.1
celery==5.3.4

# requirements-dev.txt — extra dev tools
-r requirements.txt
pytest==7.4.3
pytest-cov==4.1.0
ruff==0.1.6
mypy==1.7.0
pre-commit==3.5.0

# requirements-constraints.txt — floor versions only (allow upgrades)
Django>=4.2
psycopg2-binary>=2.9
redis>=4.0
"""

LOCK_FILE_CONCEPT = """
requirements.txt (pinned) ≈ a lock file
pip-compile (pip-tools) generates a pinned requirements.txt from requirements.in:

  # requirements.in  (abstract deps)
  Django>=4.0
  requests
  pydantic[email]

  # pip-compile outputs requirements.txt (concrete, pinned)
  # Auto-generated by pip-compile
  certifi==2023.11.17
  django==4.2.7
  pydantic==2.5.2
  pydantic-core==2.14.5
  requests==2.31.0
  ...

Poetry and uv do the same via their lockfile systems.
"""

# ─────────────────────────────────────────────────────────
# 3. venv bootstrap script
# ─────────────────────────────────────────────────────────
BOOTSTRAP_SH = """#!/bin/bash
# bootstrap.sh — create venv and install dependencies

set -euo pipefail

VENV=.venv
PYTHON=${PYTHON:-python3.11}

echo "Creating virtual environment..."
$PYTHON -m venv $VENV

echo "Upgrading pip..."
$VENV/bin/pip install --upgrade pip setuptools wheel

echo "Installing dependencies..."
$VENV/bin/pip install -r requirements.txt

if [ -f requirements-dev.txt ]; then
    echo "Installing dev dependencies..."
    $VENV/bin/pip install -r requirements-dev.txt
fi

echo "Done! Activate with: source $VENV/bin/activate"
"""

BOOTSTRAP_PS1 = """# bootstrap.ps1 — Windows PowerShell

$ErrorActionPreference = "Stop"
$VENV = ".venv"

Write-Host "Creating virtual environment..."
python -m venv $VENV

Write-Host "Upgrading pip..."
& $VENV\\Scripts\\pip install --upgrade pip setuptools wheel

Write-Host "Installing dependencies..."
& $VENV\\Scripts\\pip install -r requirements.txt

Write-Host "Done! Activate with: .venv\\Scripts\\Activate.ps1"
"""

# ─────────────────────────────────────────────────────────
# 4. Dependency resolver (simplified)
# ─────────────────────────────────────────────────────────
class SimpleDependencyResolver:
    """Educational: understand how pip resolves dependencies (simplified)."""

    def __init__(self):
        self._packages: dict[str, dict] = {}  # {name: {version, deps}}

    def add(self, name: str, version: str, deps: list[str] | None = None):
        self._packages[name.lower()] = {"version": version, "deps": deps or []}

    def resolve(self, requirements: list[str]) -> dict[str, str]:
        """Return {package: version} for all transitive deps."""
        resolved: dict[str, str] = {}
        to_resolve = list(requirements)

        while to_resolve:
            req = to_resolve.pop(0).lower()
            if req in resolved:
                continue
            pkg = self._packages.get(req)
            if not pkg:
                print(f"  WARNING: '{req}' not in registry")
                continue
            resolved[req] = pkg["version"]
            for dep in pkg["deps"]:
                if dep.lower() not in resolved:
                    to_resolve.append(dep)

        return resolved

if __name__ == "__main__":
    print("=== PipManager Usage ===")
    pip = PipManager()

    installed = pip.list_packages()
    print(f"Installed packages: {len(installed)}")
    if installed:
        sample = installed[:3]
        print(f"Sample: {[f\"{p['name']}=={p['version']}\" for p in sample]}")

    print("\n=== pip show ===")
    info = pip.show("pip")
    for k, v in info.items():
        print(f"  {k}: {v}")

    print("\n=== requirements.txt patterns ===")
    print(REQUIREMENTS_PATTERNS.strip())

    print("\n=== Dependency Resolution Demo ===")
    resolver = SimpleDependencyResolver()
    resolver.add("django",     "4.2.7", ["sqlparse", "asgiref"])
    resolver.add("sqlparse",   "0.4.4", [])
    resolver.add("asgiref",    "3.7.2", [])
    resolver.add("drf",        "3.14.0", ["django"])
    resolver.add("django-cors-headers", "4.3.0", ["django"])

    solution = resolver.resolve(["drf", "django-cors-headers"])
    print(f"Resolved: {solution}")
